version: "3"
services:
  client:
    image: "qpham01/multi-client"
    mem_limit: 64m
    hostname: client
  server:
    image: "qpham01/multi-server"
    mem_limit: 64m
    hostname: api
    env_file:
      - .env
  worker:
    image: "qpham01/multi-worker"
    mem_limit: 64m
    hostname: worker
    env_file:
      - .env
  nginx:
    depends_on:
      - server
      - client
    image: "qpham01/multi-nginx"
    mem_limit: 64m
    hostname: nginx
    ports:
      - "80:80"
