name: Deploy Frontend
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker username
        run: echo ${{ secrets.DOCKER_USERNAME }}

      - name: Docker password
        run: echo ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build test client
        run: docker build -t qpham01/client-test -f client/Dockerfile.dev ./client
      - name: Test client
        run: docker run -e CI=true qpham01/client-test npm test

      - name: Build production client
        run: docker build -t qpham01/multi-client ./client
      - name: Build production nginx
        run: docker build -t qpham01/multi-nginx ./nginx
      - name: Build production server
        run: docker build -t qpham01/multi-server ./server
      - name: Build production worker
        run: docker build -t qpham01/multi-worker ./worker

      - name: Push production client
        run: docker push qpham01/multi-client
      - name: Push production nginx
        run: docker push qpham01/multi-nginx
      - name: Push production server
        run: docker push qpham01/multi-server
      - name: Push production worker
        run: docker push qpham01/multi-worker
