name: Deploy Frontend
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t qpham01/client-test -f client/Dockerfile.dev ./client
      - run: docker run -e CI=true qpham01/client-test npm test
 
      - name: Build all components
        run: docker build -t qpham01/multi-client ./client
        run: docker build -t qpham01/multi-nginx ./nginx
        run: docker build -t qpham01/multi-server ./server
        run: docker build -t qpham01/multi-worker ./worker
        # run: zip -r deploy.zip . -x '*.git*'

      - name: Push images to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        run: docker push qpham01/multi-client
        run: docker push qpham01/multi-nginx
        run: docker push qpham01/multi-server
        run: docker push qpham01/multi-worker
